version: "2.2"
services:

  eureka:
    image: "xxpay-server:1.0.0"
    volumes:
      - /log:/log
    hostname: eureka
    ports:
    - "2000:2000"
    network_mode: "host"

  config:
    image: "xxpay-config:1.0.0"
    volumes:
      - /log:/app/log
    hostname: config
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 2000
    ports:
     - "2020:2020"
    network_mode: "host"
  service:
    image: "xxpay-service:1.0.0"
    volumes:
        - /log:/app/log
    hostname: service
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 2000
       SERVER_PORT: 3000
    ports:
      - "3000:3000"
    network_mode: "host"

  web:
    image: "xxpay-web:1.0.0"
    volumes:
        - /log:/app/log
    hostname: web
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 2000
       SERVER_PORT: 3010
    ports:
      - "3010:3010"
    network_mode: "host"

  zuul:
    image: "xxpay-gateway:1.0.0"
    volumes:
        - /log:/app/log
    hostname: zuul
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 2000
    ports:
      - "3020:3020"      
    network_mode: "host"

